//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MyJava.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMyJavaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class MyJavaBaseListener : IMyJavaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] MyJavaParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] MyJavaParser.CompilationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclaration([NotNull] MyJavaParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclaration([NotNull] MyJavaParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classOrInterfaceModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassOrInterfaceModifier([NotNull] MyJavaParser.ClassOrInterfaceModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classOrInterfaceModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassOrInterfaceModifier([NotNull] MyJavaParser.ClassOrInterfaceModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] MyJavaParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] MyJavaParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] MyJavaParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] MyJavaParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBodyDeclaration([NotNull] MyJavaParser.ClassBodyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBodyDeclaration([NotNull] MyJavaParser.ClassBodyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.methodMemberDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodMemberDecl([NotNull] MyJavaParser.MethodMemberDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.methodMemberDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodMemberDecl([NotNull] MyJavaParser.MethodMemberDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.fieldMemberDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldMemberDecl([NotNull] MyJavaParser.FieldMemberDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.fieldMemberDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldMemberDecl([NotNull] MyJavaParser.FieldMemberDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classMemberDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassMemberDecl([NotNull] MyJavaParser.ClassMemberDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classMemberDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassMemberDecl([NotNull] MyJavaParser.ClassMemberDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDeclaration([NotNull] MyJavaParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDeclaration([NotNull] MyJavaParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDeclaration([NotNull] MyJavaParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDeclaration([NotNull] MyJavaParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarator([NotNull] MyJavaParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarator([NotNull] MyJavaParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaratorId([NotNull] MyJavaParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaratorId([NotNull] MyJavaParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] MyJavaParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] MyJavaParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classOrInterfaceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassOrInterfaceType([NotNull] MyJavaParser.ClassOrInterfaceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classOrInterfaceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassOrInterfaceType([NotNull] MyJavaParser.ClassOrInterfaceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] MyJavaParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] MyJavaParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.qualifiedNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedNameList([NotNull] MyJavaParser.QualifiedNameListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.qualifiedNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedNameList([NotNull] MyJavaParser.QualifiedNameListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameters([NotNull] MyJavaParser.FormalParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameters([NotNull] MyJavaParser.FormalParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterList([NotNull] MyJavaParser.FormalParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterList([NotNull] MyJavaParser.FormalParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameter([NotNull] MyJavaParser.FormalParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameter([NotNull] MyJavaParser.FormalParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.lastFormalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLastFormalParameter([NotNull] MyJavaParser.LastFormalParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.lastFormalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLastFormalParameter([NotNull] MyJavaParser.LastFormalParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodBody([NotNull] MyJavaParser.MethodBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodBody([NotNull] MyJavaParser.MethodBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedName([NotNull] MyJavaParser.QualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedName([NotNull] MyJavaParser.QualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] MyJavaParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] MyJavaParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] MyJavaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] MyJavaParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStatement([NotNull] MyJavaParser.BlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStatement([NotNull] MyJavaParser.BlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclaration([NotNull] MyJavaParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclaration([NotNull] MyJavaParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] MyJavaParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] MyJavaParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.enhancedForControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnhancedForControl([NotNull] MyJavaParser.EnhancedForControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.enhancedForControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnhancedForControl([NotNull] MyJavaParser.EnhancedForControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] MyJavaParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] MyJavaParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] MyJavaParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] MyJavaParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] MyJavaParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] MyJavaParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreator([NotNull] MyJavaParser.CreatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreator([NotNull] MyJavaParser.CreatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreatedName([NotNull] MyJavaParser.CreatedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreatedName([NotNull] MyJavaParser.CreatedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassCreatorRest([NotNull] MyJavaParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassCreatorRest([NotNull] MyJavaParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] MyJavaParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] MyJavaParser.ArgumentsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
