//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MyJava.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MyJavaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public interface IMyJavaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilationUnit([NotNull] MyJavaParser.CompilationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilationUnit([NotNull] MyJavaParser.CompilationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclaration([NotNull] MyJavaParser.TypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclaration([NotNull] MyJavaParser.TypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classOrInterfaceModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrInterfaceModifier([NotNull] MyJavaParser.ClassOrInterfaceModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classOrInterfaceModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrInterfaceModifier([NotNull] MyJavaParser.ClassOrInterfaceModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] MyJavaParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] MyJavaParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] MyJavaParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] MyJavaParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBodyDeclaration([NotNull] MyJavaParser.ClassBodyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBodyDeclaration([NotNull] MyJavaParser.ClassBodyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>methodMemberDecl</c>
	/// labeled alternative in <see cref="MyJavaParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodMemberDecl([NotNull] MyJavaParser.MethodMemberDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>methodMemberDecl</c>
	/// labeled alternative in <see cref="MyJavaParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodMemberDecl([NotNull] MyJavaParser.MethodMemberDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fieldMemberDecl</c>
	/// labeled alternative in <see cref="MyJavaParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldMemberDecl([NotNull] MyJavaParser.FieldMemberDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fieldMemberDecl</c>
	/// labeled alternative in <see cref="MyJavaParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldMemberDecl([NotNull] MyJavaParser.FieldMemberDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>classMemberDecl</c>
	/// labeled alternative in <see cref="MyJavaParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassMemberDecl([NotNull] MyJavaParser.ClassMemberDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>classMemberDecl</c>
	/// labeled alternative in <see cref="MyJavaParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassMemberDecl([NotNull] MyJavaParser.ClassMemberDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDeclaration([NotNull] MyJavaParser.MethodDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDeclaration([NotNull] MyJavaParser.MethodDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDeclaration([NotNull] MyJavaParser.FieldDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDeclaration([NotNull] MyJavaParser.FieldDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarator([NotNull] MyJavaParser.VariableDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarator([NotNull] MyJavaParser.VariableDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableInitializer([NotNull] MyJavaParser.VariableInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableInitializer([NotNull] MyJavaParser.VariableInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayInitializer([NotNull] MyJavaParser.ArrayInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayInitializer([NotNull] MyJavaParser.ArrayInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaratorId([NotNull] MyJavaParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaratorId([NotNull] MyJavaParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] MyJavaParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] MyJavaParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrInterfaceType([NotNull] MyJavaParser.ClassOrInterfaceTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrInterfaceType([NotNull] MyJavaParser.ClassOrInterfaceTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] MyJavaParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] MyJavaParser.PrimitiveTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.qualifiedNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedNameList([NotNull] MyJavaParser.QualifiedNameListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.qualifiedNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedNameList([NotNull] MyJavaParser.QualifiedNameListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameters([NotNull] MyJavaParser.FormalParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameters([NotNull] MyJavaParser.FormalParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameterList([NotNull] MyJavaParser.FormalParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameterList([NotNull] MyJavaParser.FormalParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameter([NotNull] MyJavaParser.FormalParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameter([NotNull] MyJavaParser.FormalParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.lastFormalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLastFormalParameter([NotNull] MyJavaParser.LastFormalParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.lastFormalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLastFormalParameter([NotNull] MyJavaParser.LastFormalParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodBody([NotNull] MyJavaParser.MethodBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodBody([NotNull] MyJavaParser.MethodBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedName([NotNull] MyJavaParser.QualifiedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedName([NotNull] MyJavaParser.QualifiedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] MyJavaParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] MyJavaParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] MyJavaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] MyJavaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStatement([NotNull] MyJavaParser.BlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStatement([NotNull] MyJavaParser.BlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVariableDeclaration([NotNull] MyJavaParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVariableDeclaration([NotNull] MyJavaParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MyJavaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MyJavaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.enhancedForControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnhancedForControl([NotNull] MyJavaParser.EnhancedForControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.enhancedForControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnhancedForControl([NotNull] MyJavaParser.EnhancedForControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] MyJavaParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] MyJavaParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] MyJavaParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] MyJavaParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] MyJavaParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] MyJavaParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.creator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreator([NotNull] MyJavaParser.CreatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.creator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreator([NotNull] MyJavaParser.CreatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.createdName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreatedName([NotNull] MyJavaParser.CreatedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.createdName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreatedName([NotNull] MyJavaParser.CreatedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.classCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassCreatorRest([NotNull] MyJavaParser.ClassCreatorRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.classCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassCreatorRest([NotNull] MyJavaParser.ClassCreatorRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyJavaParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] MyJavaParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyJavaParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] MyJavaParser.ArgumentsContext context);
}
